### ISSUE TITLE
Nove verzije

### ISSUE THREAD

**Issue by voltino** [nbakaric/Croatian-sylabification#1]
Dosta je prošlo od objavljivanja ovog koda, ne znam jesi li još aktivan na githubu, ali koja je potrebna verzija regexa da ovo proradi?

**Comment by nbakaric** [comment]
Ne znam točno koja je verzija regexa (tamo negdje 2017 je bila u pitanju), no nedavno sam vrtio kod preko Jupyter Notebooka uz manja ažuriranja za Python 3 i nisam imamo problema s regexom.

**Comment by voltino** [comment]
Ja sam pokušavao na pythonu 2.7 i 2.7.9, ali nisam nikako mogao instalirati regex kojeg podržavaju. Pa sam probao na 3.10 što je očito pre novo jer mi se javlja sljedeći error
![image](https://github.com/user-attachments/assets/12efd59a-ed1a-4955-ba3e-9cd10a61962f)
Sad ne znam je li namjenjeno ovako imati input file 
![image](https://github.com/user-attachments/assets/22056be0-dd8a-4f67-8203-75d416e543d8)
ili ovako
![image](https://github.com/user-attachments/assets/f6db57e3-ff67-4f8d-813d-412c658f3122)

**Comment by IamMusavaRibica** [comment]
> Sad ne znam je li namjenjeno ovako imati input file  

Sudeći po kodu, ovako prvo  
Usto, linija 461 nema smisla: `rijeci = rijeci.split("\t")[-3].strip()`, ali ionako je zakomentirana

Ne postoji ugrađeni library `regex` u Pythonu 3. Moguće je instalirati putem naredbe u command promptu:
```
py -3.9 -m pip install regex
```
(naravno ako se radi o nekoj drugoj verziji, promijeniti)
~~ili promijeniti importe u: `import codecs, re, re as regex, operator`~~

**Comment by nbakaric** [comment]
Sorry, nisam stigao odgovoriti ranije.

Tako je, regex treba instalirati. Problem je bio što native re modul ne uzima u obzir preklapanja rezultata (#regex module required for overlapped matches). Ne znam kakva je sada situacija, no u Jupyteru sam regex bez problema pozvao, mislim da ga on sam instalira...

Skripta očekuje za input UTF-8 datoteku koji čita red po red, a red sadrži jednu rečenicu. Konkretno, ja sam radio analizu nad brzalicama, brojalicama i sličnim kratkim žanrovima pa mi je svaki red bio jedna brzalica.

Output sadrži više datoteka jer mi je trebao i frekvencijski popis n-grama i slogova za svaki red i za svaki korpus (cijelu datoteku).
